### ISSUE TITLE
Questions/Feedback

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#1088]
* Having items without a category makes them impossible to be rendered in the preview.

* Setting the rarity feels a little hidden, since it cannot be done through the detail page, and is a necessary step in order to publish the wearable

**Comment by nicosantangelo** [comment]
- There's a disconnect between the collection detail page and the item editor. There's no easy way to go back to the collection page from the editor but it's required to use both to complete an item. Also, the concept of complete (done) items does not exist on the editor but it's necessary for publishing a collection.
As a more concrete example, if I add a new item to a collection I have to:
1. Go to the editor to add the category/rarity
2. Realise you have to go back to the collection detail page (not the item detail page)
3. Set price and beneficiary there to be able to publish

- Selecting a collection on the editor is a bit confusing. I think we need to do something with the right side. Right now it's really hard to tell what's selected
![image](https://user-images.githubusercontent.com/692077/94745484-2c930900-0351-11eb-8faa-55bfb5ab82ea.png)

**Comment by nachomazzara** [comment]
Check https://docs.google.com/spreadsheets/d/1UXWwM3QyqKaHYpTqvYj_7HObxEdxr028BVZ9pwSvs54/edit#gid=1493479271
