### ISSUE TITLE
List names

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1136]
It shouldn't add any functionality other than showing the action links.

* Name
  * Show person icon near to the already avatar's name in use.
* Being Assigned
* Assigned to
* Actions:
  - Assign/Edit
  - Use as alias

**Comment by nicosantangelo** [comment]
# How to go about developing this issue

The general action points for this issue are:
1. Add a new page and tab for `Names`
2. Grab the ENSs of the connected wallet and show them in the new table. Remember that this module exists on the state right now, called `ENS` and lives on `moules/ens`. For example the selector for the ENSs wallet is `getENSByWallet`
3. Update `handleFetchDomainListRequest` found on `modules/ens/sagas` which is the method that handles the request for the user's ENSs. Right now this method works as intended BUT it cant determine from which land each ENS is. For each ENSs fetched, we need to update the `landId`
4. Add pagination. For this you'll need to use the `ui` module, which is already being used for things like the dashboard.

That's about it for this PR, the rest of the UI should be drawn but not implemented (like `use as alias`)
