### ISSUE TITLE
Add a confirm modal when de-assigning a name.

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1216]
Show a confirmation modal after prompt for the transaction explaining what is going to happen.

Also, the animation on hover shows the `-` circle first.

<img width="390" alt="Screen Shot 2020-12-17 at 12 33 27" src="https://user-images.githubusercontent.com/7549152/102508414-1e0ce180-4064-11eb-8972-20acb9809e59.png">

**Comment by nicosantangelo** [comment]
We can maybe reuse (or at least check) the confirmation we have in place for clearing the activity on the `/activity` page

![image.png](https://images.zenhubusercontent.com/601dcbd9715e60c791100933/472d4aff-f1a8-4097-91e7-c273dfab8a66)

**Comment by nachomazzara** [comment]
Remember to redirect the user to the activity (and add the transaction there too)

**Comment by fzavalia** [comment]
The transaction was already being added to the history so no changes were needed there
