### ISSUE TITLE
The Builder cannot deploy to district land using either the estate UpdateManager or UpdateOperator wallets. 

### ISSUE THREAD

**Issue by cfravel** [decentraland/builder#1253]
This is hindering district decoration.

**Comment by cazala** [comment]
looking into it, @cfravel I sent you a DM via Slack, it would be helpful for me to have the addresses of the accounts having that issue, so I can impersonate them and debug from there

**Comment by cfravel** [comment]
Replied by DM

**Comment by cfravel** [comment]
i think that i had the concept of this wrong.
The issues I'm seeing are elaborated in #1263 and  #1264
I am now thinking that this issue 1253 might just be incorrect.
But if you have started to investigate it and find any merit to keeping it, please so, else close and go to 1263, 1264.
Thanks!

**Comment by cazala** [comment]
Closed in favor of #1263
