### ISSUE TITLE
Builder dApp is retrieving all the content server entities

### ISSUE THREAD

**Issue by marcosnc** [decentraland/builder#1258]
After some usage analysis on the Peer content server we discovered that the Builder dApp is retrieving all the Content server entities which results in a very high load to the server.
We think that's caused by this code:
https://github.com/decentraland/builder/blob/b83144c73af1d5d14bf841a23a851217132911a9/src/modules/deployment/sagas.ts#L262
If the `pointers: coords` parameter is an empty list, the client library is consuming all the entities without any filter.
The Platform team is going to change that part of the client lib to avoid this issue, but we need the Builder to avoid that kind of calls in order to avoid an error in the Builder.

**Comment by nachomazzara** [comment]
Closed By #1260
