### ISSUE TITLE
Builder cannot deploy to Aetheria land north or east of 150

### ISSUE THREAD

**Issue by cfravel** [decentraland/builder#1263]
The Builder cannot deploy to Aetheria land x > 150 || y > 150, leaving about 2000 parcels unable to be decorated by the Builder.   This is a problem for the district and for privately-allocated land operators whos assigned plots are > 150 in x or y.
This is now a problem blocking getting the Aetheria District fully populated, including with the results of the Cyberpunk Contest cosponsored by Aetheria.

Steps to reproduce:
Log into MetaMask and select the Aetheria district estate's UpdateOperator wallet.
Go into builder
Create a scene or select an existing scene
[Publish]
Note that some Aetheria land does properly show north and east of 150.
however you cannot place the scene north or east of 150.

dcl info 151,151  (decentraland@next) does show that the Estate updateOperator is properly assigned to the estate.

**Comment by nachomazzara** [comment]
Related to https://github.com/decentraland/explorer/issues/1624

**Comment by cazala** [comment]
This is fixed now in prod, the Atlas allow you to select land beyond 150
