### ISSUE TITLE
Idle stop playing after changing bodyShape

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1315]

**Comment by nicosantangelo** [comment]
This is actually working correctly. What I've noticed is that the animation just plays once @nachomazzara 
Maybe we can ask the Unity team how to change that? (if it's a problem)

**Comment by nachomazzara** [comment]
@pravusjif @pbosio any help?

**Comment by pbosio** [comment]
we might have to debug that. as far as I know the avatar is always playing an animation, if it's on the ground is idle animation if it's not then falling animation 🤔
did you try setting again the idle animation with another timestamp?
