### ISSUE TITLE
A new search should scroll to the top of the assets list. 

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#132]
Plus each asset might need a title to check matches

**Comment by belohlavek** [comment]
Plus each asset might need a title to check matches?

**Comment by nicosantangelo** [comment]
It's kind of hard to tell what the match was sometimes

**Comment by belohlavek** [comment]
you are talking about highlighting the piece of the string that matches the search?

**Comment by nicosantangelo** [comment]
Yes, or something of the sort. I want to "fix" these cases:

![image](https://user-images.githubusercontent.com/692077/52413520-2dbf5480-2ae2-11e9-9c77-3942ecd7ffff.png)

I don't understand at first glance why those are my top results, because I know there are trees on the asset list
