### ISSUE TITLE
Show a link to the explorer once the collection is published and has minted items

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#1339]
We might need to check that the item is indeed minted to the current connected address

**Comment by nachomazzara** [comment]
Why do you think that this is useful? Should only the creator or managers/minters will be able to see the link? 

Maybe we can add a link to check the collections in the explorer  with `WITH_COLLECTION` flag  for creators and curators

**Comment by nicosantangelo** [comment]
> Maybe we can add a link to check the collections in the explorer with WITH_COLLECTION flag for creators and curators

This is what I meant! maybe it's a good idea to have a way for curators to see the item in-world to jugde it. My general idea was to consider if it was useful to see it in action, moving in the world, without having to mint it

**Comment by nachomazzara** [comment]
I would add it even if you have not minted it
