### ISSUE TITLE
Polygon name support

### ISSUE THREAD

**Issue by Sidetalker** [decentraland/builder#1395]
![image](https://user-images.githubusercontent.com/1299693/120148611-1ffbd480-c1ae-11eb-9bd9-0fc6fd9c1f80.png)

**Comment by HPrivakos** [comment]
The screenshot is out of context, I was meaning to report the fact that there is currently a bug which makes it impossible to click on the claim button, Polygon names was a response to another non related question.
![Screenshot_2021-05-31_07-03-53](https://user-images.githubusercontent.com/16406638/120142641-e2fc0600-c1de-11eb-932d-fb05eaf7ba47.png)

**Comment by Sidetalker** [comment]
Whoops, sorry no time to scroll but always time to report

**Comment by nachomazzara** [comment]
Won't in Polygon soon. That error should be fixed.

**Comment by Sidetalker** [comment]
My goodness that is not details

**Comment by Sidetalker** [comment]
Reopen please
