### ISSUE TITLE
Import/Export project

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#14]
Using a custom save file

**Comment by twaldorf** [comment]
Here are scribbles from my discussion with Mat yesterday on the UX
![Builder sketches - export(3)](https://user-images.githubusercontent.com/7725089/55878807-91620e80-5b73-11e9-9266-2832f0d480e1.png)
![Builder sketches - export(2)](https://user-images.githubusercontent.com/7725089/55878809-932bd200-5b73-11e9-8baf-d52d1f636153.png)
![Builder sketches - export home 1](https://user-images.githubusercontent.com/7725089/55878924-d5edaa00-5b73-11e9-97ce-fdfad56045b9.png)
![Builder sketches - export home 2](https://user-images.githubusercontent.com/7725089/55878954-e43bc600-5b73-11e9-9939-2a0b60ebb5b5.png)
