### ISSUE TITLE
Disable icon to edit thumbnail in "add representation mode" to avoid confusion

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#1416]
- If the user creates a wearable with only one representation, we should disable the thumbnail edition when adding the missing representation.

![Screen Shot 2021-06-25 at 17.55.03.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/9615c5ca-3250-4ebd-bdbd-7f3ec5ab0415)

**Comment by Sidetalker** [comment]
Please update issue above

**Comment by cazala** [comment]
updated 👍
