### ISSUE TITLE
Higher resolution images

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#1454]
Currently we are storing `thumbnail` an `image` as 256x256 (the former with a transparent background and the latter with a rarity-colored background).

Opensea uses 1024x1024 images, so it would be nice to generate a higher res `image`. 

Before doing this, we should check how much space would that higher res image take from the 2MB allocated per entity and decide if it's worth it. 

If so, we should then change a little bit the way we store thumbnails and generate images:
+ We should store `thumbnail` as a 1024x1024 image (currently it is 256x256)
+ When publishing the collection we should generate the `image` as a 1024x1024 (this already happens but as 256x256)
+ There's a new last step we need to add: resize down each `thumbnail` to 256x256 before uploading to catalyst.

**Comment by LautaroPetaccio** [comment]
Closing it as we've already increased the size of the images.
