### ISSUE TITLE
Can't edit (add a representation) from `new Item` 

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1460]
If the item is published, I can't add a representation by using the `new item` button at the collections tab.

Expected behavior: "Convert" the `Add new item` into an item edition.

https://images.zenhubusercontent.com/325377244/d1191a8c-32bd-46a5-b78d-9466149a2ef1/screen_recording_2021_06_30_at_16_08_48.mov

**Comment by cazala** [comment]
https://forum.decentraland.org/t/collection-lol-meme-face-created-by-lefty-is-ready-for-review/1281
