### ISSUE TITLE
Use content server instead of builder-server if the item is in the catalyst

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1486]
If the item is in the catalyst, we should use  `https://peer.decentraland.org/content/contents/` instead of `https://builder-api.decentraland.org/v1/storage/contents/`. 

Example: `https://peer.decentraland.org/content/contents/QmWWqMKjfKHnAouoMd8NjL9NZ8xGnuo1sTG8NdAdFazbDi` instead of 
`https://builder-api.decentraland.org/v1/storage/contents/QmWWqMKjfKHnAouoMd8NjL9NZ8xGnuo1sTG8NdAdFazbDi`

**Comment by nicosantangelo** [comment]
Do we know if there's someone else using the builder-api/storage endpoint? to decide where we should fix it, if on the front-end or in the API itself

**Comment by nachomazzara** [comment]
It should be in the FE, it is mostly used to get the URL for the thumbnail
