### ISSUE TITLE
Allow using the same .glb name for the female and male representation 

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1488]
If you add a representation with the same `.glb` name. The first representation added gets overrided

**Comment by ShibuyaMartin** [comment]
[https://app.zenhub.com/files/162741822/941fe308-8258-4901-a983-4600b6dd8fa6/download](https://app.zenhub.com/files/162741822/941fe308-8258-4901-a983-4600b6dd8fa6/download)
