### ISSUE TITLE
Once error occurs in CreateAssetModal, it can't be closed

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#1511]
Once error occurs in CreateAssetModal, it can't be closed

**Comment by nicosantangelo** [comment]
it's a bit of a pain to test, but to check if it's still happening/fix it, we can force a `throw new Error()` somewhere in the Modal

**Comment by fzavalia** [comment]
Does it refer to the `CreateAssetPackModal`

**Comment by fzavalia** [comment]
Tried throwing an error on the onSubmit of AssetImporter and the close button still works

**Comment by fzavalia** [comment]
https://github.com/decentraland/builder/pull/1529

**Comment by fzavalia** [comment]
When the modal fails, it also causes the sidebar to show an indefinite loading

**Comment by fzavalia** [comment]
Fixed on same PR
