### ISSUE TITLE
Fix Ms Edge item spawning

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#153]

**Comment by menduz** [comment]
wat?

**Comment by belohlavek** [comment]
First error: `PBRMaterial#updateData ReferenceError: 'queueMicrotask' is not defined`
Then when spawning: ` 0,0: Error loading GLTF Unable to load assets from dcl://0_0_qmtest/e6fa9601-3e47-4dff-9a84-e8e017add15a/Chair_02/Chair_02.glb: Failed to load scene. Function expected`

**Comment by menduz** [comment]
Damn, how do we fight a JS engine inconsistency?
