### ISSUE TITLE
Add collections/items ready for review

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1546]
- Use endpoint `POST /curations` from the builder-server to set the collection ready for review.

- Get the curations list from `GET /curations` .

- Use the published collections + the curation list to display the `pending` `rejected` and `approved`

**Comment by fzavalia** [comment]
@nachomazzara Should we identify in the curation list collections that have changes in them from the new ones? Does the curator care if they are reviewing a collection with changed items that has already been published?

**Comment by nachomazzara** [comment]
If it is possible we can show it somehow

**Comment by fzavalia** [comment]
Working on changes that were defined on yesterdays meeting
```
Show status color orb on mint items modal.
Show warning message when minting or setting the collection on sale when it is under review.
	"Some items have changes that have not been approved yet".
Update Approve and Reject buttons on the item editor to remove the ambiguity between collection and curation.
	"Approve/Reject Collection" and "Approve/Reject Curation" instead of only "Approve/Reject".
Show only changed items as under review instead of all, Non changed should show as synced (green).
Remove "Disable" button.
```
