### ISSUE TITLE
Create Third Party collection items

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1563]
- We should allow drag & drop items without collection.
  - If the item is being dragged & dropped into a third party collection, we need to remove the `rarity` (null) and add a default `urn`. This URN is generated based on the third party record, the collection urn and a default generated URN for the item.
  - If the item is being removed from the third party collection, we need to remove the urn (null).
- The item creation modal (ONLY FOR THIRD PARTY ITEMS) should have the following fields:
  - The name of the item
  - The category of the item
  - The URN of the item.
- Once we save the item, we need to fill & check if the URN is valid.
  - We need to check if the urn is well-formed.
  - We need to check if the urn is unique for that specific collection.

**Comment by nicosantangelo** [comment]
@LautaroPetaccio Can I ask you to update this issue and https://github.com/decentraland/builder/issues/1570 if necessary? to accommodate for the new requirements. For example, we don't have the creation of the `ADD ITEMS` button:
![image](https://user-images.githubusercontent.com/692077/150878891-f60b3443-a44d-40cd-92db-fa8a7c421dfc.png)

anywhere

**Comment by LautaroPetaccio** [comment]
URNs will be assigned automatically when creating a third party item.
Removing an item from a Third Party collection so the item is out of a collection will not be permitted, but we need an issue for that.
