### ISSUE TITLE
Builder throws error when trying to download scene zip

### ISSUE THREAD

**Issue by cfravel** [decentraland/builder#1582]
steps to reproduce:

1. Go to https://builder.decentraland.org
2. Create a new 1x1 scene
3. Add a Genesis City pack tree to it
4. Click on the download button
// Expected:   you get a downloaded .zip file
// Actual: scene gets to Downloading somewhere between 89% to 100%, but then nothing more
// and the Console shows this error:

rollbar.min.js:1 TypeError: Cannot read properties of null (reading 'generateInternalStream')
    at generateAsync (2.7dbc81c2.chunk.js:1)
    at N.<computed> (2.7dbc81c2.chunk.js:1)
    at 2.7dbc81c2.chunk.js:1
    at m (2.7dbc81c2.chunk.js:1)
    at p (2.7dbc81c2.chunk.js:1)
    at c (2.7dbc81c2.chunk.js:1)
    
   rollbar.min.js:1 The above error occurred in task b
    created by takeLatest([Request] Export project, b)
    created by _w
    created by _w
Tasks cancelled due to error:
takeLatest([Request] Export project, b)
takeLatest(Create project from template, p)
takeLatest(Duplicate project, m)
takeLatest(Edit project, f)
takeLatest(Share project, h)
takeLatest(Import project, y)
takeLatest([Request] Load public project, v)
takeLatest([Request] Load projects, g)
takeLatest([Request] Load manifest, _)
takeLatest([Success] Login, O)
takeLatest(Delete project, E)

**Comment by cfravel** [comment]
This is blocking many of the users I am supporting in Aetheria and elsewhere from being able to make some adjustments in the SDK, such as rotation or spawn points.

**Comment by cazala** [comment]
Fixed by #1583
