### ISSUE TITLE
Homepage Project card enhancements

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#164]
- Hover animation on `...`
- Order from newest to oldest
- Increase clickable area of the `...`
- Confirm project deletion

All debatable

**Comment by belohlavek** [comment]
would edit project open the same modal?

**Comment by belohlavek** [comment]
When should increase the clickable area of the ...

**Comment by nicosantangelo** [comment]
> Should we have an edit project option?

@belohlavek I think it's a good idea but we might want to track it in a separate issue
