### ISSUE TITLE
Update catalyst endpoint to check item's green orb (synced status)

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1713]
The platform team will [remove some endpoints](https://github.com/decentraland/catalyst-client/pull/194)

We need to change what we have `client.fetchAllDeployments`:
- Items: https://github.com/decentraland/builder/blob/master/src/modules/entity/sagas.ts#L29
- Scenes:  https://github.com/decentraland/builder/blob/master/src/modules/deployment/sagas.ts#L278 to this

To  this: `ContentClient.fetchEntitiesByPointers({type: wearable, pointers: [urn1, urn2, ...]})`

**Comment by cyaiox** [comment]
Resolved in: https://github.com/decentraland/builder/pull/2736
