### ISSUE TITLE
Manage TP Item curation checkboxes

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#1726]
- [ ] We should disallow checking TP item checkboxes for items that have different ItemCuration statuses. Meaning that if an item requires a different TopPanel button action, it should not be checkeable
- [ ] Check the max amount of items that can be selected and disallow checking more

![image.png](https://images.zenhubusercontent.com/601dcbd9715e60c791100933/b1cbe352-89c8-45fe-92a5-abe658557778)

Depends on #1725

**Comment by LautaroPetaccio** [comment]
The item editor won't have checkboxes anymore.
