### ISSUE TITLE
Add the proper ItemCuration approval flow

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#1728]
We need to "duplicate" the collection approval flow, keeping in mind that TP items can only be approved and rejected.

- We should probably duplicate or reuse the different components like `ApprovalFlow`
- We should check the saga that's doing the collection flow and copy/reuse it for TP Items (`handleInitiateApprovalFlow`)
- We should only do the approval flow for the selected items

Related #1725 1726

**Comment by LautaroPetaccio** [comment]
Closing this issue as the items will be curated in batch.
