### ISSUE TITLE
Add a a new parapgrah saying that the collection name can't be edited once the colleciton is published

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1755]
Add this between the second and third paragraphs. So it should be the new third paragraph.

```
You won’t be able to change the name of the collection. Please ensure it’s spelled correctly and doesn’t violate intellectual property rights.
```

![image.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/17b18e86-50bc-4ddf-aa6c-e0789452982d)

**Comment by dhanushreddy291** [comment]
I have updated in three languages. 
https://github.com/dhanushreddy291/builder/commit/ad5dc358f1503b76a72509f482c6f431d5f509df

Can I send a PR? 🙃
