### ISSUE TITLE
Remove MAX_PUBLISH_ITEM_COUNT

### ISSUE THREAD

**Issue by juanmahidalgo** [decentraland/builder#1812]
Remove `MAX_PUBLISH_ITEM_COUNT` from `src/modules/thirdParty/utils.ts` and its usages from `src/components/ThirdPartyCollectionDetailPage/ThirdPartyCollectionDetailPage.tsx` since we won't need that anymore now that we have the merkle tree check.

**Comment by RyanLuong1** [comment]
Hi there, I am interested in tackling this I am able to.

**Comment by juanmahidalgo** [comment]
> Hi there, I am interested in tackling this if I am able to.

Hi @RyanLuong1! Yeah, please feel free to send a PR with those changes!

In the `ThirdPartyCollectionDetailPage.tsx` we can remove the `Info` component entirely and for the `PAGE_SIZE` variable used there, you can just set a number like `15`.

**Comment by RyanLuong1** [comment]
Hi Juan, thank you for letting me take on this! I did the changes and submitted my pull request. Let me know if there is anything wrong with my changes and what I can do to fix it.
