### ISSUE TITLE
Move opensea api call to the builder-server and builder-client

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#1816]
- Add [method](https://github.com/decentraland/builder-client/blob/main/src/client/BuilderClient.ts) to hit the server.
- Move endpoint to the builder-server

**Comment by fzavalia** [comment]
Creating new endpoints in the builder-server that will inject the api key when calling open sea.
These endpoints will not act as a proxy, they will have their own schemas to support future migrations to other vendors.
