### ISSUE TITLE
Update the "Buy Slot Modal" copy

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#1872]
The current modal looks like this
![image.png](https://images.zenhubusercontent.com/601dcbd9715e60c791100933/9c96f8c7-d486-4a00-8ce5-3dc9da455146)

We should:

- [ ] update the text at the end to look like this:

```
The cost of each slot is USD 500.
The total cost will be USD xxx and it will be payed in :arrow_up_small: MANA.
Slippage tolerance is of 3%, so if while executing this transaction there is a 3% or higher increase in the MANA price, no slots will be purchased and nothing will be charged.
```

changing the values to revolve around USD.

- [ ] Round up the slippage value

**Comment by juanmahidalgo** [comment]
Putting this one on hold until it [this proposal](https://governance.decentraland.org/proposal/?id=f69c4d40-aaaf-11ec-87a7-6d2a41508231) ends and we know if we need to update the modal or deprecate it.
