### ISSUE TITLE
Add more selection options to the list of TP items

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/builder#1972]
## 🎉 Description

We currently have a select all items option that selects all items, independently of their status. For example, if the user has a lot of items to push changes to, and also has items that hasn't published, the select all that we currently have will select both items, the ones to be pushed and the unfinished ones that the user might not want to publish. The same issue also happens with items that were already published and can't be re-published.

Add options for:
- Selecting all items to publish
- Selecting all items to push changes

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
This was solved when we introduced the filters for the tp items

![image.png](https://images.zenhubusercontent.com/61e56f8bfe61d4326945f317/31cad3e7-d3a6-456d-a3bc-e26d4678da36)

Closing the issue for now

**Comment by juanmahidalgo** [comment]
This was solved when we introduced the filters for the tp items

![image.png](https://images.zenhubusercontent.com/61e56f8bfe61d4326945f317/31cad3e7-d3a6-456d-a3bc-e26d4678da36)

Closing the issue for now
