### ISSUE TITLE
Can't access an item's detail from the URL

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/builder#2075]
## 🎉 Description

Accessing  an item's detail through its URL doesn't work, but if the user navigates through the site and accesses an item's details, it works.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 🔢 Steps To Reproduce Issue [ Good To Have ]
1. Open a collection with an item
2. Go to an item's details
3. Refresh the site and the details won't load.

![image.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/5d64736d-e628-434c-a91c-47ce18b33380)
![image.png](https://images.zenhubusercontent.com/60d9e2eae14d1d56b7547674/d336d04d-4497-4540-9996-d41b82955fa5)

**Comment by juanmahidalgo** [comment]
It has been fixed a week ago. Closing the issue for now.
