### ISSUE TITLE
Adding an items with external texture is counting the texture as part of the limits

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#210]
GLB with external textures (that have been reused) should not count to the limits.

**Comment by belohlavek** [comment]
<img width="1246" alt="screen shot 2019-02-20 at 15 23 16" src="https://user-images.githubusercontent.com/1307029/53114836-7be14880-3523-11e9-9f38-bb2c05193378.png">

Here's what you get to do with the current limits, feels underwhelming

Please give this issue a high priority

**Comment by menduz** [comment]
In order to do so, we will have to fork the babylon gltf loader

**Comment by belohlavek** [comment]
For reference this could be achieved if not limited by textures:
<img width="1300" alt="screen shot 2019-02-20 at 17 36 59" src="https://user-images.githubusercontent.com/1307029/53122771-3a0dcd80-3536-11e9-874d-1cc0b91ed5ce.png">
