### ISSUE TITLE
Disable the "USE AS ALIAS" button when the user does not have a profile

### ISSUE THREAD

**Issue by fzavalia** [decentraland/builder#2125]
When clicking this button when the user has not created a profile yet will:

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/fb837606-a714-4f7f-8602-b0e8c4970e96)

Show a message without the name that is replacing.

![image.png](https://images.zenhubusercontent.com/5ea09af31c23030cb8e249b8/e493b199-9b19-4108-a987-aba861dcef9a)

Fail with a 404 when confirming because there is no profile to assign that name.

TASK:

Disable the button and add a tooltip or message indicating that you have to create you avatar in [play.decentraland.org](https://play.decentraland.org) first

**Comment by VeitchM** [comment]
I started working in this issue
