### ISSUE TITLE
Allow push changes when items are being curated

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/builder#2142]
## 🎉 Description

Up to know, push changes aren't allowed if there's a set of items being curated, that is, items that were published or had their changes pushed. This is not a UX issue, as the curator can review multiple items when curating them.

To comple this task:
- Make the changes necessary in the backend to allow pushing the changes when there are items to be curated (this is done by a request to the curations endpoint)
- Make the changes in the UI to allow this behavior.

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
Reviewed with @LautaroPetaccio and decided to close it for now since there was a confusion at the moment of reporting an error with this flow which doesn't seem to have an issue. We tested a few scenarios and they all allowed to push changes even there were other items under reviewed.
