### ISSUE TITLE
Code rename: Unselect should be called deselect

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#222]
Unselect is used to qualify something that has not been selected, not something that was selected and isn't anymore.

**Comment by cazala** [comment]
<img width="633" alt="screen shot 2019-02-25 at 12 30 50 am" src="https://user-images.githubusercontent.com/2781777/53312641-a1a87d80-3894-11e9-97c6-faafa9f2a497.png">

mm to me _unselect_ sounds more natural, specially in a software context, like _"unselect a checkbox"_

**Comment by nicosantangelo** [comment]
Hmm, searching around I found [this](https://english.stackexchange.com/questions/18465/unselect-or-deselect/18516) question that kind of supports what I was going for.

Plus, if it means something, a google search for the same sentence but using deselect yields more results:

![image](https://user-images.githubusercontent.com/692077/53337381-8889e600-3901-11e9-96b8-f22255a13556.png)


![image](https://user-images.githubusercontent.com/692077/53337358-790a9d00-3901-11e9-8dc1-00d2626bda4d.png)

And using radio instead of checkbox:

![image](https://user-images.githubusercontent.com/692077/53337399-950e3e80-3901-11e9-8647-7486bace590b.png)

---

Obviously not sure as this is mostly a hunch on my part

**Comment by cazala** [comment]
make sense, I guess [we have a winner](https://trends.google.com/trends/explore?geo=US&q=unselect,deselect) (:
