### ISSUE TITLE
Can't add second Male/Female representation for wearable after publishing

### ISSUE THREAD

**Issue by EibrielInv** [decentraland/builder#2296]
Hi! When editing a wearable after being published is not possible to add the secondary Male or Female representation (the option don't show up)

Steps to reproduce (on a published wearable):
- Upload a new file for the Male representation
- At this point you will be unable to find an option to upload a new file for the Female representation

**Comment by EibrielInv** [comment]
Looks like is possible to add the representation by clicking again on the "Edit" button on the Item page

Maybe the button should change the label to "Add Male/Female representation"

**Comment by LautaroPetaccio** [comment]
Closed as the UI changed.
