### ISSUE TITLE
[Creation][ItemEditor] Show a toast after creating an Item and being redirected to the ItemEditor

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#2350]
Show a `toast` in the `bottom-left` side after the user successfully creates an emote and is redirected to the ItemEditor.

This toast has a link to return to the selected collection details.

<img width="1440" alt="editor owner" src="https://user-images.githubusercontent.com/3170051/206188388-cd73f1ab-4ea3-4262-9944-7fe9b83e58b9.png">

**Comment by juanmahidalgo** [comment]
Let's implement Option A.

**Comment by cyaiox** [comment]
Adds a button to return to the `selected collection` details page in the `ItemEditorPage` > `RightPanel` component.
