### ISSUE TITLE
Collections with multiple items show up multiple times in curation page

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#2358]
If collection has more than one item, it shows up several times when using the MVMF filter in the curation page:

<img width="1180" alt="Screen Shot 2022-10-07 at 15 00 11" src="https://user-images.githubusercontent.com/2781777/194620965-64295912-efc4-46a2-80df-14f66587e848.png">

**Comment by cyaiox** [comment]
Resolved in PR: https://github.com/decentraland/builder-server/pull/610
