### ISSUE TITLE
Stop showing message to edit collection when it's already complete

### ISSUE THREAD

**Issue by nicorajcodcl** [decentraland/builder#2412]
## 🎉 Description

As a user, when I create a collection in the Builder, in the collection page I always see the message in the image below, regardless of the status of the items in the collection. 
What should happen is that, if all the items in the collection are complete and don't require any action from the user (in other words, the collection is ready to publish), then this message shouldn't appear.

![image.png](https://images.zenhubusercontent.com/63074b6c3d1e525cad8f134a/851b2b03-1198-45d5-9f41-b96cd7155603)

* [ ] 🐛 This is a bug report.
* [X] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
- Step 2
- Step 3
...
```

**Comment by cyaiox** [comment]
Removed in: https://github.com/decentraland/builder/pull/2537
