### ISSUE TITLE
Improve Operator description 

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/builder#2419]
Improve builder UI by adding a description that the `operator` is the `update operator` to avoid confusion.

Option: `Update operators can **only** deploy and update scenes and can be removed at any time.`

![Screen Shot 2022-11-09 at 14.32.27.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/9dbb2bf7-7314-4650-80dc-ea5d04d486d8)

**Comment by cyaiox** [comment]
Update the page: `https://.../land/:id/operator`
Tasks:
- [ ] Update title to: `Set Update Operator`
- [ ] Update description below the title to: `You are setting an update operator for <b>:landName</b>.<br />Update operators can <b>only</b> deploy and update scenes and can be removed at any time.`

**Comment by cyaiox** [comment]
Issue closed because the text change could lead to more confusion for the end user
