### ISSUE TITLE
Preview should be disabled while editor is loading

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#254]
![kapture 2019-02-28 at 0 34 09](https://user-images.githubusercontent.com/1307029/53539549-bed98800-3af0-11e9-864c-c5df3a9118f2.gif)

We need to avoid this broken state ☝️

**Comment by cazala** [comment]
Also entering Preview when the sidebar is hidden is broken, theres a gap at the bottom:

<img width="1043" alt="screen shot 2019-02-28 at 5 21 47 pm" src="https://user-images.githubusercontent.com/2781777/53595949-5ab0d580-3b7d-11e9-8ed9-da660be373bd.png">
