### ISSUE TITLE
Please provide scaling handles as well as move and rotate

### ISSUE THREAD

**Issue by cfravel** [decentraland/builder#323]
One may need to adjust the size, or even the proportions, of an object to accommodate the needs of the scene.
Please add an option to turn on scaling handles, too.

**Comment by belohlavek** [comment]
Scaling is off intentionally for now as we want to keep it simple with a focus on unexperienced decorators. We'll release a formal announcement if that changes!

Please provide more details regarding "move and rotate handles"

**Comment by belohlavek** [comment]
Scaling is on, congrats!
