### ISSUE TITLE
Please provide "plane" handles on the move (and future size) tools

### ISSUE THREAD

**Issue by cfravel** [decentraland/builder#324]
In order to move something around on the ground plane you have to move it in two steps, as movements are constrained to 1 dimension
Many 3D tools provide 3 little squares that allow movement constrained to 2 dimensions.
(You can see these in Blender, Second Life, etc.)

Sizing tools have similar mechanisms, but you also get a "size in all dimensions) option

**Comment by belohlavek** [comment]
You can currently move freely by dragging an item. One directional axis are optional!

**Comment by belohlavek** [comment]
Are we ok on this one @cfravel?
