### ISSUE TITLE
Align shortcut tooltip

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#327]
<img width="306" alt="Screen Shot 2019-03-11 at 11 59 07 AM" src="https://user-images.githubusercontent.com/2781777/54133596-1e8b3980-43f5-11e9-86de-d9ae5bbf2c4b.png">

**Comment by belohlavek** [comment]
<img width="1306" alt="Screen Shot 2019-03-11 at 18 06 49" src="https://user-images.githubusercontent.com/1307029/54202164-3246a680-44ae-11e9-962f-b292c03a34a7.png">

can we also align those?
