### ISSUE TITLE
Starting tooltip for limits is unhelpful

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#334]
There is an automatic tooltip from #300 that points out scene limit panel when the user loads scenes for the first time. 

<img width="191" alt="Screen Shot 2019-03-13 at 12 13 22 PM" src="https://user-images.githubusercontent.com/7725089/54295453-6e9b0500-4589-11e9-90aa-5ba1bd3a5ea9.png">

We think the automatic tooltip for scene limits adds too much UX overhead for new users without helping them understand limits.

Our subpar solution is to remove this tooltip. Alternatives would be staggering the appearance (triggering it only when a few objects have been added, or on a timer) or triggering it after other tooltips are closed. These both seem worse than just removing the tooltip.

 In the future, limits will be explained better. Mat has some early quick ideas: (this is not a design req lol)
![Screen Shot 2019-03-13 at 12 14 08 PM](https://user-images.githubusercontent.com/7725089/54295513-8a061000-4589-11e9-8aa6-0b788a12c671.png)

**Comment by belohlavek** [comment]
So are we going for removing the tooltip? Should this be done for the mvp?

**Comment by twaldorf** [comment]
Yeah, we are removing the tooltip. Should be done when possible, this won't block the launch.
