### ISSUE TITLE
Undo and redo buttons

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#336]
We have support for undo and redo in the Builder from #6.

We think that more decorator users would be able to discover undo and redo by exposing them in the interface. In user tests, all but a few users (so ~15 users) clicked the `Reset Orientation` button while trying to `undo`. Adding `undo` and `redo` buttons may help clear that confusion as well.

Alternatively, we could turn the `Reset Orientation` button into an `undo` button and relegate `Reset Orientation` to just a shortcut. This is viable because `Reset Orientation` is a more advanced feature that shortcut users are likely to want, whereas simpler decorators don't seem to understand it (although they often could benefit from it, which is why it should be exposed in the interface imo).

Design from Mat:
![Screen Shot 2019-03-13 at 1 13 46 PM](https://user-images.githubusercontent.com/7725089/54300725-d6eee400-4593-11e9-86e6-ae236186a71c.png)

Mat has more deets. What else should be included in issues like this? More design files? More UX opinion?

**Comment by belohlavek** [comment]
Looking good, this is enough info ;)

**Comment by cazala** [comment]
Regarding the "reset orientation", that button also re-snaps the item back to the grid, and once we have scaling in place, it would also reset the item's scale

**Comment by abarmat** [comment]
Deprecated
