### ISSUE TITLE
Remove Sign Up button from email collection in tutorial

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#338]
<img width="670" alt="Screen Shot 2019-03-14 at 11 35 04 AM" src="https://user-images.githubusercontent.com/7725089/54372184-34953600-4651-11e9-8c53-681abd1dc02a.png">

#301 implemented a new slide containing information about the contest and optional email collection, as per requirements. The purpose of the slide is to prepare users to submit scenes to the contest and increase retention by collecting more user emails for marketing followup.

Currently, the layout of the slide splits up the email CTA by including it in the top paragraph, above the contest graphic. Feedback on this is that separating the CTA from the field is confusing. The signup CTA should be moved below, to just above the email field.

Additionally, the slide could be improved by adding the Submit to Contest button inline in place of the `"Submit to contest"` text as an example. To increase the instructional value of the slide, the contest graphic could be replaced by an .mp4 of a user moving to click the `Submit to contest` button.

discussion in slack

**Comment by twaldorf** [comment]
Update, the only change we're going to make is removing the `Sign Up` button in the field. The `Done` button should submit the form, unless it's empty. This solution is a compromise that we'll test in the near future against Mat's initial design.

**Comment by belohlavek** [comment]
ok!

**Comment by belohlavek** [comment]
Are we still inlining the contest button in the text?

**Comment by twaldorf** [comment]
Just talked to Mat, yes! Something like this

![Screen Shot 2019-03-15 at 11 38 13 AM](https://user-images.githubusercontent.com/7725089/54443423-f7937700-4716-11e9-841b-bd211ab60b1a.png)
