### ISSUE TITLE
Contest submission isn't enabled after clearing out-of-bounds items

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#351]
#309 possibly introduced a bug where the `Submit to contest` button isn't correctly re-enabled when the user has deleted or moved out-of-bounds objects. This can be fixed by refreshing, but I have reproduced it on Chrome and Firefox and a few people have used Intercom to inquire about it.

**Comment by twaldorf** [comment]
Hmm, now I'm having trouble reproducing this, will investigate more

**Comment by nicosantangelo** [comment]
@twaldorf You're right, if you move an object out of bounds and *delete it* the submission button isn't updated

**Comment by twaldorf** [comment]
Still getting a lot of reports on this, any ideas @nicosantangelo @cazala ?

**Comment by nicosantangelo** [comment]
Following the discussion on Slack, I can't seem to be able to reproduce this anymore either

**Comment by cazala** [comment]
I was able to reproduce it on prod. Place seceral items outside of the bounds and then delete them, sometimes it gets stuck.

**Comment by nicosantangelo** [comment]
Another way to break it:
![out-bounds](https://user-images.githubusercontent.com/692077/54618420-49176b00-4a63-11e9-81be-e9bcfdbe9d1a.gif)

**Comment by belohlavek** [comment]
Closing this one, let's open a more specific issue for Nico's case when we are able to reproduce it (neither Juan nor I could do it).
Deleting an item out of bounds is now fixed.
