### ISSUE TITLE
Some users cannot submit scenes due to a Network Error

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#366]
We've gotten about 10 of these reports, all with reasonable parcel sizes under the limits. Often these users are able to submit some scenes but not a particular scene. Sample console error below.

![Screen Shot 2019-03-18 at 12 40 53 PM](https://user-images.githubusercontent.com/7725089/54554013-d25a6f00-4989-11e9-8fc6-ff1f22740d7d.png)

I think Juanca was going to grab this one later

**Comment by abarmat** [comment]
I tried this fix that can fix the problem https://github.com/decentraland/builder-contest-server/pull/9

**Comment by twaldorf** [comment]
Looks like it!
