### ISSUE TITLE
Warn users away from .zone

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#375]
Users are spending time in the test deployment, making and submitting scenes. To prevent this, we should add a banner, as mentioned by Dani, to the top of the .zone version.

Copy incoming

**Comment by belohlavek** [comment]
Got a temporal copy in all languages already

**Comment by twaldorf** [comment]
For context and posterity, .zone performs better in China, probably due to Cloudflare being blocked aggressively, so we are treating that as a prod server now
