### ISSUE TITLE
Redesign Builder homepage

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#377]
We drop about 22% of users at the homepage. For first-time users, the homepage fails in a few ways:
1. It doesn't show the experience of the Builder or the output of the Builder (what can I do here? What will I gain?)
2. It shows a very 'cold' state when there are no projects and buries the most important row of buttons—the `TEMPLATE` row—at the bottom of the stack.

Design: 
![1 home empty copy 3](https://user-images.githubusercontent.com/7725089/54887171-32f41b00-4e66-11e9-902f-a7cb6dd8ed70.png)

Copy: https://docs.google.com/document/d/1uPAvyZYkyE52O32XC17k5i9sqgmFZfDjaetH5sidzdw/edit?usp=sharing

Translations: [CN and KR here](https://docs.google.com/document/d/1R3FFztIWLDfolX2eo8k1NHXZZMQK36WSwy50GBnQMkk/edit?usp=sharing)

**Comment by belohlavek** [comment]
`The [B] solution of re-ordering the stack of buttons, if possible, should affect only new users. If that's not feasible, the new user experience takes priority, and the TEMPLATES row should still be moved up top for all users.`

Can you expand on this?

**Comment by twaldorf** [comment]
Yes! Ideally,
As a new user, I see the `TEMPLATES` row above the `PROJECTS` row, because I have no projects.
As a returning user with projects, I see the `PROJECTS` row above the `TEMPLATES` row, because I have projects.

However, if that's not feasible as part of a "quick fix" band-aid here, we can stick to:

As a user, I see the `TEMPLATES` row above the `PROJECTS` row.

**Comment by belohlavek** [comment]
What about the video cta?

**Comment by twaldorf** [comment]
Removed. The video doesn't add new information and provides a distraction/complication for the user to "overcome" when all we really want to do is let them edit as soon as possible, minimizing the time-to-value of the Builder.

**Comment by twaldorf** [comment]
This is all being updated by Mat

**Comment by nicosantangelo** [comment]
I finished this story here: https://github.com/decentraland/builder/tree/feat/ISSUE-377 but I'm not sure if it's still useful

**Comment by twaldorf** [comment]
Updated with copy and design and translation status @belohlavek
