### ISSUE TITLE
KR translation

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#380]
I'm trying to copy and paste the raw files but all I see are the wrong characters, which makes me nervous, but also, passing around raw text files makes me nervous

This is what AriM sent me, I'm looking for the original JSON file:
[ko_json_raw.txt](https://github.com/decentraland/builder/files/2990175/ko_json_raw.txt)

**Comment by belohlavek** [comment]
We merged this yesterday right?

**Comment by twaldorf** [comment]
Yep!
