### ISSUE TITLE
Update contest price in USD on the tutorial banner

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#385]
Add a `(over 50,000 USD!)` to the tutorial end page like in the homepage.

Home
<img width="1080" alt="home" src="https://user-images.githubusercontent.com/140773/54770021-32971e00-4be1-11e9-9aa0-4cb51ee59745.png">

Tutorial
<img width="579" alt="tutorial" src="https://user-images.githubusercontent.com/140773/54770026-362aa500-4be1-11e9-9425-0a50faa1e0f1.png">

**Comment by belohlavek** [comment]
@abarmat how are we on this?
