### ISSUE TITLE
Optimize color of `Submit to contest` button

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#386]
The colorful `Submit to content` button may be more effective if it matches all the other buttons in the flow. We could change the button to be the gradient red from the tutorial flow. The effect of this would be a reduction in the dropoff from the editor to contest submission, where we lose 80% of users.

**Comment by twaldorf** [comment]
![image](https://user-images.githubusercontent.com/7725089/54776479-9b34c980-4be6-11e9-942a-791698f8027a.png)

**Comment by belohlavek** [comment]
Are we naming it Add to Contest again @twaldorf ?
