### ISSUE TITLE
Optimize tutorial flow by allowing users to skip it

### ISSUE THREAD

**Issue by twaldorf** [decentraland/builder#387]
We lose about 8% of users in the tutorial. We could optimize it by allowing users to skip it, with a `Skip` button on the first slide, to the left of the `Next` button.

**Comment by nicosantangelo** [comment]
I think adding a `Skip` button might look like you're trying to skip the current slide (even if next does that). Maybe we can add the close button (`X`) on the top right?
Moreover, skipping the tutorial might be a problem because you can't open it again

**Comment by twaldorf** [comment]
Yeah, I think the idea is that the `Skip` button would take you to that last slide, with the contest info. Thoughts on that behavior?

**Comment by belohlavek** [comment]
Designs please

**Comment by twaldorf** [comment]
Design:
![2 editor tutorial copy (1)](https://user-images.githubusercontent.com/7725089/54880631-02d45a00-4e1d-11e9-875f-b1598299ede2.png)
