### ISSUE TITLE
Placing an item sometimes does not highlight it

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#403]

**Comment by twaldorf** [comment]
It also prevents selection until another object is selected. Placing a second object allows you to select the first object.

![2771db3f9bd4c05fa65ccf44752f82dc](https://user-images.githubusercontent.com/7725089/56607552-2edf2880-65df-11e9-962c-605df8baa624.gif)

**Comment by nicosantangelo** [comment]
@belohlavek Is this still relevant?

**Comment by abarmat** [comment]
Closing this issue moving to https://github.com/decentraland/unity-client/projects/2
