### ISSUE TITLE
Cloud save UI

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#430]
We also should do pagination and filtering in the homepage @cazala

**Comment by twaldorf** [comment]
Here are scribbles from my discussion with Mat yesterday on the UX
![Builder sketches - export(3)](https://user-images.githubusercontent.com/7725089/55878807-91620e80-5b73-11e9-9266-2832f0d480e1.png)
![Builder sketches - export(2)](https://user-images.githubusercontent.com/7725089/55878809-932bd200-5b73-11e9-8baf-d52d1f636153.png)
![Builder sketches - export(1)](https://user-images.githubusercontent.com/7725089/55878815-9626c280-5b73-11e9-87ef-40ce8d84c95a.png)
![Builder sketches - export](https://user-images.githubusercontent.com/7725089/55878816-97f08600-5b73-11e9-80de-7fb6fcb7c65e.png)

**Comment by belohlavek** [comment]
#546 and #547
