### ISSUE TITLE
Featured pack highlighting

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#463]
The Builder should reserve space to highlight a special pack or promotion. This should use a tag, not a category, so that users can still browse those pack items as part of the full categories.

- [x] Definitions
`The Builder should show users (who already have projects) news about item packs.
`

- [x] Designs
Mat is working on this solution as of Thursday, 25 April

- [ ] Implementation

**Comment by twaldorf** [comment]
The interim design for this is [here](https://app.zeplin.io/project/5c2a5a6920eaa20beb77984f/screen/5caf6e7afe244b013f901aea), utilizing the banner pattern.

**Comment by belohlavek** [comment]
Are we doing this @abarmat @LucasGondolo82 ?

**Comment by LucasGondolo82** [comment]
We should do this or by prepare for the upcoming Asset Packs.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nicosantangelo** [comment]
Did we do this @abarmat @belohlavek ?

**Comment by abarmat** [comment]
We have implemented marking "new" asset packs #687 in that fulfill the need that was the original source of this issue.

**Comment by abarmat** [comment]
Closing the issue.
