### ISSUE TITLE
Placement of scene

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#510]
In this stage you select to what LAND / Estate you are uploading your scene by the use of an interactive placement page.

- [x] Query the LAND / Estates you have permissions to deploy to. The ones you are one of these roles: Owner, UpdateOperator, UpdateManager

- [ ] Display a Map from where to select where/how to place your current scene (research if we can include the Atlas in here)

- [ ] Rotate your scene placement

**Comment by abarmat** [comment]
@LucasGondolo82 please add any relevant UX design to the issue

**Comment by LucasGondolo82** [comment]
https://sketch.cloud/s/7bVQ8/a/npaplW/play
