### ISSUE TITLE
Add auth middleware to builder server

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#542]
- [ ] GET /projects (paginado)
- [ ] GET /projects/:id
- [ ] PUT /projects/:id
- [ ] DELETE /projects/:id
- [ ] POST /projects/:id/media

No POST, uuids are generated client side so we can reuse logic used for cloud synced and offline scenes

- [ ] GET /deployments
- [ ] PUT /deployments/:id
- [ ] GET /deployments/:id
- [ ] DELETE /deployments/:id

**Comment by cazala** [comment]
Closed in favor of https://github.com/decentraland/builder-server/issues/24
