### ISSUE TITLE
Unauthorized Page

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#554]
`/editor/:projectId` for projects that are not the users'

**Comment by nicosantangelo** [comment]
Right now the unauthorised user sees the 404 page
![image](https://user-images.githubusercontent.com/692077/65801251-10152d00-e14f-11e9-9178-0e86d77be4af.png)
is that enough?

**Comment by abarmat** [comment]
Looks like enough to me

**Comment by belohlavek** [comment]
It is enough for what we have on production

This issue tracks the fact that we don't really handle this case individually, this is still very low priority tho
