### ISSUE TITLE
Duplicated scene has no thumbnail

### ISSUE THREAD

**Issue by cazala** [decentraland/builder#613]
Repro:

While logged in and in dashboard:
- Duplicate a scene (it will have a thumbnail)
- Refresh the page (thumbnail is gone)

**Comment by belohlavek** [comment]
proposal:
if base64: convert to blob using helper and send to /media
if remote, fetch image as blob and send to /media

This will fix:
- The case where two duplicated projects have linked thumbnails
- The case where a duplicated project has no thubnail
