### ISSUE TITLE
Publish to LAND not allowing to use Estates

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#645]
### Description

* Problem: When I try to deploy a scene to a parcel in one of my Estates I cannot proceed.
* Why: The Estates I own appear as greyed out.
* Expected: I should see as available to deploy both Parcels and Estates I own or have proper permissions.

### Marketplace View
<img width="273" alt="marketplace" src="https://user-images.githubusercontent.com/140773/63567806-558b7c80-c549-11e9-8c8a-72e1269eceba.png">

### Builder View
<img width="649" alt="builder" src="https://user-images.githubusercontent.com/140773/63567807-558b7c80-c549-11e9-94e3-5b38905125d6.png">

### Request
The request used to fetch assets is the following:
https://api.decentraland.org/v1/addresses/0xef38f892e4722152fd8edb50cd84a96344fd47ce/parcels

Note: It is only bringing back parcels.

**Comment by abarmat** [comment]
I think I has to do with this commit that had the endpoint to fetch both LAND and EST where you have permissions to deploy being refactored but not sure what ended being the final endpoint => https://github.com/decentraland/marketplace/commit/e362f2acb737275696ac210477a223ff5a017ae9

**Comment by cazala** [comment]
Fixed by #646
