### ISSUE TITLE
Publish to LAND color on map

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#649]
The color we're using for owned LAND on the builder represents LAND on sale on the Marketplace

**Builder**
![image](https://user-images.githubusercontent.com/692077/63867909-12d40500-c98c-11e9-965e-b0d7a295ee64.png)

**Marketplace**
![image](https://user-images.githubusercontent.com/692077/63867957-21bab780-c98c-11e9-849c-caa2529b2dd3.png)

**Comment by belohlavek** [comment]
I'd call this one an enhancement or something else. The colors are intentional and were reviewed by mat /shrug

**Comment by nicosantangelo** [comment]
Ok! but maybe it was an oversight? having different colors across our products doesn't make much sense, right?.

Maybe instead of waiting for mat to re-review (two weeks from now) it we could pre-emptively change it to be consistent

What do you think? @belohlavek @abarmat
