### ISSUE TITLE
Publish next LAND icon

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#650]
Maybe it's too late (if so we can close this) but the icon we're using is the same we use to focus on the Marketplace, which is a bit confusing. Maybe we could change it for this?

**Builder**
![image](https://user-images.githubusercontent.com/692077/63872491-2aaf8700-c994-11e9-9af8-9d60504138b9.png)

**Marketplace**
![image](https://user-images.githubusercontent.com/692077/63872502-313dfe80-c994-11e9-9812-a7b11528bcef.png)

**Comment by belohlavek** [comment]
`Maybe we could change it for this?`
For which one? I think it's ok to change it!

**Comment by nicosantangelo** [comment]
I had an icon in mind at the time and silly me forgot to add it to the PR 😞 
I think we need a @mat signal here

**Comment by mat** [comment]
What’s up? 😃

**Comment by abarmat** [comment]
Maybe we can use the same icon we used for finding a random LAND that we used in the Auction
