### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#653]
There are a few inconsistencies with the Spanish translation

1) Land instead of LAND. Also the word `Landowners` is not being translated?

<img width="574" alt="Schermafbeelding 2019-08-28 om 13 09 49" src="https://user-images.githubusercontent.com/692077/63873658-5fbcd900-c996-11e9-9a09-457acf06d800.png">

2) Lack of the starting exclamation sign **sometimes**

With
<img width="607" alt="Schermafbeelding 2019-08-28 om 13 10 33" src="https://user-images.githubusercontent.com/692077/63873770-8d098700-c996-11e9-9cb5-7182f9f69c97.png">

Without
<img width="574" alt="Schermafbeelding 2019-08-28 om 13 11 01" src="https://user-images.githubusercontent.com/692077/63873774-90047780-c996-11e9-89d6-0748d5486816.png">

3) `de la esta`

<img width="509" alt="Schermafbeelding 2019-08-28 om 13 21 11" src="https://user-images.githubusercontent.com/692077/63873872-c641f700-c996-11e9-8d83-97bdd5c88f7e.png">

4) The word `Despublicar` does not exist

![image](https://user-images.githubusercontent.com/692077/63878032-1de46080-c99f-11e9-8cb5-6b52fd8c9dc2.png)

**Comment by belohlavek** [comment]
`The word Despublicar does not exist` 😂
