### ISSUE TITLE
Importing a scene with errors does not give any feedback

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#655]
I made a mistake dragging a .zip files to the `Import scene` feature and ended up with this modal:

 
<img width="556" alt="Schermafbeelding 2019-08-28 om 13 11 57" src="https://user-images.githubusercontent.com/692077/63874114-49fbe380-c997-11e9-9ffb-308639b325e9.png">

which does not give me any feedback on what happened

**Comment by belohlavek** [comment]
This is fixed on the custom asset packs branch

**Comment by belohlavek** [comment]
@nicosantangelo can you review this one?
