### ISSUE TITLE
Scaling should work with world transform

### ISSUE THREAD

**Issue by belohlavek** [decentraland/builder#672]
Currently affected by local transform (rotation)

**Comment by abarmat** [comment]
What is this?

**Comment by belohlavek** [comment]
Local transform means that the scale is affected by the rotation, so for example the Y axis will be pointing diagonally somewhere if the object is rotated

World transform is what we use for the other gizmos, so the position gizmo stays straight even after rotating an object

Both local and wold transforms are useful, most software allow toggling between them, we should do too (Unity)
