### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#695]

**Comment by belohlavek** [comment]
Let's talk about changes to be made @nicosantangelo

**Comment by nicosantangelo** [comment]
I would:
- Add a mention to the builder-server somewhere, as is required to run the frontend now
- I think some of the vars on the `env` section are deprecated like `REACT_APP_ASSETS_URL=https://builder-packs-prod.now.sh`.
Having the basic requirements on the README is super cool but if it's a pain to maintain we could just avoid it by linking to the .env.example? we could point out a few URLs tho.

Anything else you have in mind?

**Comment by nicosantangelo** [comment]
I can't really push the changes as I'm waiting for some dependencies to be published but I don't have an answer from every party

**Comment by nicosantangelo** [comment]
@abarmat Any news on this?
