### ISSUE TITLE
Set asset as ground throws

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#699]

**Comment by abarmat** [comment]
**Excepted behaviour:**
Let me click the "set as ground" flag on the asset

**Steps to reproduce:**
1) Click the Create new Asset Pack button
2) Import one or more assets into the importer
3) Review items and click on the set as ground button

<img width="513" alt="set-ground" src="https://user-images.githubusercontent.com/140773/65396609-687ab200-dd7e-11e9-8710-3741214400d9.png">

**Comment by belohlavek** [comment]
Got this one ✅
