### ISSUE TITLE
Camera goes crazy after creating new asset pack

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#700]
**Steps to reproduce:**

1) Create a new Asset Pack on the sidebar
2) Import only ONE asset and set as ground
3) Finish the import process, save the asset pack

The camera goes loco

Attachment:
[Screen Recording 2019-09-20 at 15.54.14.mp4.zip](https://github.com/decentraland/builder/files/3640333/Screen.Recording.2019-09-20.at.15.54.14.mp4.zip)

**Comment by belohlavek** [comment]
Can't reproduce :/

**Comment by nicosantangelo** [comment]
Seems like it fixed itself™, closing to avoid clutter
