### ISSUE TITLE
Pressing the `z` key doesn't work after a few key combinations

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#704]
In macOS pressing the shortcuts for taking a screenshot or a video:
`cmd+shift+4`
`cmd+shift+5`
and then pressing
`esc`
disables the `z` key on inputs.

This could be a bigger problem if there's other combinations doing the same

**Comment by belohlavek** [comment]
Any ideas on what is causing this?

**Comment by nicosantangelo** [comment]
Maybe the editor/Babylon is swallowing inputs again?
