### ISSUE TITLE
Asset editing

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#708]
Editing assets is a tad weird:
1) When I create a new asset I cannot edit it (clicking the little thumb does nothing)
2) But, the same action does work when editing the asset pack. Worse still, there's no indication that it'll work (like a `cursor: pointer` or a pencil icon)
3) On the asset edition modal page itself, not having a "SAVE" button is weird because to save my changes I have to *go back*. It's not intuitive at all

[edit-asset.mov.zip](https://github.com/decentraland/builder/files/3644188/edit-asset.mov.zip)

**Comment by belohlavek** [comment]
I'd add a label that indicates that assets are click-able and I'd add the save button, what do you think @nicosantangelo?

**Comment by nicosantangelo** [comment]
I think those two things are more than enough.
Is it possible/desirable to edit assets on create?

**Comment by belohlavek** [comment]
We should investigate that and do it separately as it involves hooking a bunch of stuff
