### ISSUE TITLE
Unpublish option is hard to find and I can't edit the name

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#746]
This is directly related to this modal's text:
![image](https://user-images.githubusercontent.com/692077/65994406-968c8000-e469-11e9-90dd-0278865392e1.png)

I wanted to change my scene's name and I couldn't find the unpublish action anywhere. So I think we could divide this question in two:
1. Should we allow for scene name changes after the scene has been published?
2. Should we have a clearer path for scene unpublication? Mostly because it's really hard to connect the scene list with the scene unpublish, and it's on another page behind a `hover` action

I think this has been discussed but not "in paper" before

**Comment by belohlavek** [comment]
`Should we allow for scene name changes after the scene has been published?`

Yes as long as we mark the scene as dirty afterwards

`Should we have a clearer path for scene unpublication?`

Coming soon in the next builder redesign

**Comment by abarmat** [comment]
Let's turn this issue into allowing scene name changes and create other issue for the path to scene publication to be tackled on redesign, what do you think? @nicosantangelo

**Comment by nicosantangelo** [comment]
@abarmat Great!
