### ISSUE TITLE
Font weight accessibility

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/builder#747]
I think the font-weight we use for some of our texts is a bit too thin, causing it to be hard to read and not super accesible (if you don't have perfect vision)

Ex:
<img width="429" alt="Screenshot 2019-10-01 at 16 42 03" src="https://user-images.githubusercontent.com/692077/65994856-a9538480-e46a-11e9-84a2-92fd1213c666.png">

Maybe we can bump it up from `100` to `200`? What do you guys think?

<img width="393" alt="Screenshot 2019-10-01 at 16 41 55" src="https://user-images.githubusercontent.com/692077/65994889-b5d7dd00-e46a-11e9-8d79-5cb8a8862827.png">

cc: our mat

**Comment by belohlavek** [comment]
There's a chrome devtools helper to measure this right?

**Comment by belohlavek** [comment]
<img width="336" alt="Screen Shot 2019-10-01 at 17 21 48" src="https://user-images.githubusercontent.com/1307029/65997559-fc7c0600-e46f-11e9-9634-bed76888e19d.png">
It was contrast, don't think it helps

**Comment by nicosantangelo** [comment]
There are a few extensions that (supposedly) help with accessibility checks we can maybe try those?

If I'm being honest I'm using my poor vision as an indicator here which might not be the best metric

**Comment by abarmat** [comment]
I'll tell mat, I don't think he is in GitHub. A bump doesn't look bad at all as long as we do it consistently in the other similar text sections. Let check with him though.
