### ISSUE TITLE
Triangle count does not update when multiple items of the same type are placed on the scene

### ISSUE THREAD

**Issue by abarmat** [decentraland/builder#828]

**Comment by abarmat** [comment]
Video -> [triangles.mp4.zip](https://github.com/decentraland/builder/files/3825095/triangles.mp4.zip)

**Comment by pbosio** [comment]
<img width="683" alt="Screen Shot 2019-11-19 at 11 35 06" src="https://user-images.githubusercontent.com/4195708/69155536-a9fab580-0ac0-11ea-9e4a-7eeb43a3289b.png">
Metrics related to meshes are sometimes not updated
