### ISSUE TITLE
error when npm run start

### ISSUE THREAD

**Issue by gzponline** [decentraland/builder#952]
copy the config as readme.md to .env file 
but after npm run start ,some error 
![image](https://user-images.githubusercontent.com/12186221/77749923-d66da200-705d-11ea-9461-f78387f66232.png)
![image](https://user-images.githubusercontent.com/12186221/77749958-e5545480-705d-11ea-873c-e9c339b1e0c9.png)

so Need I change the .env to WHAT  I only run project local....

**Comment by cazala** [comment]
Hi @gzponline, which version of typescript are you using? If you are using VSCode, you can open any file ending in `.ts` and check in the bottom right corner:

<img width="582" alt="Screen Shot 2020-03-30 at 11 24 58 AM" src="https://user-images.githubusercontent.com/2781777/77923943-7ce1bf00-7279-11ea-8485-2d34b14f14b5.png">
